pipelines:
  branches:
    development:
      - step:
          caches:
            - node
          image: atlassian/pipelines-awscli 
          script:
            - npm install
            - npm test
            - npm run deploy