export const FETCH_PRODUCT_BEGIN = 'FETCH_PRODUCT_BEGIN'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED'

export const SET_FILTER = 'SET_FILTER'

export const SET_BLUE_BACKGROUND = 'SET_BLUE_BACKGROUND'
export const SET_DEFAULT_BACKGROUND = 'SET_DEFAULT_BACKGROUND'