version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0
jobs:
  build:
    docker: 
      - image: circleci/node:8.10
      - image: circleci/python:2.7-jessie
    steps: 
      - checkout
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependecies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Set environment vars based on branch
          command: bash ./set-env.sh
      - run:
          name: Build with parcel
          command: npm run build
      - run:
          name: Install awscli
          command: sudo pip install awscli
workflows: 
  version: 2.1
  prod: 
    jobs:
      - build: 
          filters:
            branches:
              only:
                - develop