version: 2

jobs:
  build:
      docker:
        - image: node:8.11.1
      steps:
        - checkout
        - restore_cache:
            name: Restore NPM package cache
            key: dependency-cache-{{ checksum "package-lock.json" }}
        - run:
            name: Npm dependencies
            command: npm install
        - run:
            name: Set environment vars based on branch
            command: bash ./set-env.sh
        - run:
            name: Build with parcel
            command: npm run build
        - persist_to_workspace:
            root: ~/
            paths:
              - dist
        - save_cache:
            name: Save NPM package cache
            key: dependency-cache-{{ checksum "package-lock.json" }}
            paths:
              - node_modules
  deploy:
    docker:
      - image: cibuilds/aws:1.16.43
    steps:
      - attach_workspace:
          at: ~/
      - run: 
          command: ls
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 cp . s3://karazann.com --recursive --exclude \"report.html\" --cache-control 86400
          #command: aws s3 sync generated-site/docs s3://circle-production-static-site/docs/ --delete
workflows: 
  version: 2
  FrontEnd: 
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop