version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:8.10
    steps: 
      - checkout
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          name: Restore NPM package cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependecies
          command: npm install
      - save_cache: # special step to save the dependency cache
          name: Save NPM package cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Set environment vars based on branch
          command: bash ./set-env.sh
      - run:
          name: Build with parcel
          command: npm run build
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: aws s3 cp dist s3://karazann.com --recursive --exclude \"report.html\" --cache-control 86400
workflows: 
  version: 2
  FrontEnd: 
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop