export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE'

export const SET_FILTER = 'SET_FILTER'

export const SELECT_PRODUCT = 'SELECT_PRODUCT'

/*  Auth  */

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT = 'LOGOUT'

/*  UI  */

export const OPEN_NEW = 'OPEN_NEW'
export const CLOSE_ALL = 'CLOSE_ALL'
export const OPEN_AVATAR = 'OPEN_AVATAR'
export const TOGGLE_THEME = 'TOGGLE_THEME'
export const OPEN_PUSH_NAV = 'OPEN_PUSH_NAV'
export const OPEN_NOTIFICATIONS = 'OPEN_NOTIFICATIONS'